const scripts = [
  [
    {
      name: '戏中戏中戏',
      from: '★ 原创',
      tags: ['小品'],
      duration: 10,
    },
  ],
  [
    {
      name: '你好，打劫',
      from: '饶晓志作品',
      tags: ['先锋'],
      duration: 120,
      bgImage: 'scripts/nhdj.webp',
    },
  ],
  [
    {
      name: '暗恋·桃花源',
      from: '赖声川作品',
      tags: ['爱情', '悲剧'],
      duration: 120,
      bgImage: 'scripts/althy.webp',
    },
  ],
  [
    {
      name: '乌龙山伯爵',
      from: '开心麻花作品',
      tags: ['爱情', '喜剧'],
      duration: 120,
      bgImage: 'scripts/wlsbj.webp',
    },
  ],
  [
    {
      name: '从前有座山',
      from: '飞那儿剧团作品',
      tags: ['先锋'],
      duration: 30,
      bgImage: 'scripts/cqyzs.webp',
    },
    {
      name: '金陵十三钗',
      from: '★ 严歌苓原著改编',
      tags: ['战争', '女性'],
      duration: 20,
      bgImage: 'scripts/jlssc.webp',
    },
    {
      name: '潜伏',
      from: '电视剧潜伏节选',
      tags: ['谍战'],
      duration: 15,
      bgImage: 'scripts/qf.webp',
    },
    {
      name: '聂耳小提琴的前世传奇',
      from: '国家宝藏S2作品',
      tags: ['革命'],
      duration: 15,
      bgImage: 'scripts/nextq.webp',
    },
  ],
  [
    {
      name: '9102',
      from: '飞那儿剧团作品',
      tags: ['先锋'],
      duration: 25,
      bgImage: 'scripts/9102.webp',
    },
    {
      name: '压迫',
      from: '丁西林作品',
      tags: ['民国', '喜剧'],
      duration: 20,
      bgImage: 'scripts/yp.webp',
    },
    {
      name: '酒后',
      from: '丁西林作品',
      tags: ['民国', '喜剧'],
      duration: 20,
      bgImage: 'scripts/jh.webp',
    },
    {
      name: '金漆雕木大神龛',
      from: '国家宝藏S2作品',
      tags: ['革命'],
      duration: 15,
      bgImage: 'scripts/jqdmdsk.webp',
    },
    {
      name: '鸡兔同笼',
      from: '刘添祺作品',
      tags: ['亲情'],
      duration: 30,
      bgImage: 'scripts/jttl.webp',
    },
  ],
  [
    {
      name: '点名风波',
      from: '★ 原创',
      tags: ['小品'],
      duration: 10,
    },
    {
      name: '觉醒年代',
      from: '★ 剧版觉醒年代改编',
      tags: ['革命'],
      duration: 20,
      bgImage: 'scripts/jxnd.webp',
    },
    {
      name: '谁杀死了周日',
      from: '喜剧大赛S1作品',
      tags: ['喜剧'],
      duration: 10,
      bgImage: 'scripts/ssslzr.webp',
    },
  ],
  [
    {
      name: '青铜仙鹤',
      from: '国家宝藏S3作品',
      tags: ['古装'],
      duration: 10,
      bgImage: 'scripts/qtxh.webp',
    },
    {
      name: '瞎了一只眼',
      from: '丁西林作品',
      tags: ['民国', '喜剧'],
      duration: 15,
      bgImage: 'scripts/xlyzy.webp',
    },
    {
      name: '时间都去哪儿了',
      from: '喜剧大赛S1作品',
      tags: ['喜剧'],
      duration: 15,
      bgImage: 'scripts/sjdqnl.webp',
    },
    {
      name: '风声',
      from: '★ 网剧风声改编',
      tags: ['谍战'],
      duration: 60,
      bgImage: 'scripts/fs.webp',
    },
  ],
  [
    {
      name: '警察与我之蛇我其谁',
      from: '喜剧大赛S2作品',
      tags: ['喜剧'],
      duration: 15,
      bgImage: 'scripts/swqs.webp',
    },
    {
      name: '三块钱国币',
      from: '丁西林作品',
      tags: ['民国', '喜剧'],
      duration: 15,
      bgImage: 'scripts/skqgb.webp',
    },
    {
      name: '少爷与小姐',
      from: '喜剧大赛S2作品',
      tags: ['喜剧'],
      duration: 15,
      bgImage: 'scripts/syyxj.webp',
    },
    {
      name: '花生瓜子',
      from: '子兮话剧社作品',
      tags: ['先锋'],
      duration: 20,
    },
    {
      name: '你好，疯子',
      from: '饶晓志作品',
      tags: ['先锋'],
      duration: 120,
      bgImage: 'scripts/nhfz.webp',
    },
    {
      name: '一出不好戏',
      from: '喜剧大赛S1作品',
      tags: ['喜剧'],
      duration: 10,
      bgImage: 'scripts/ycbhx.webp',
    },
    {
      name: '赵氏孤儿',
      from: '演员的诞生S1作品',
      tags: ['古装'],
      duration: 15,
      bgImage: 'scripts/zsge.webp',
    },
    {
      name: '警察与我',
      from: '喜剧大赛S2作品',
      tags: ['喜剧'],
      duration: 10,
      bgImage: 'scripts/jcyw.webp',
    },
    {
      name: '打开打不开的窗',
      from: '乌镇青赛2023作品',
      tags: ['先锋'],
      duration: 30,
      bgImage: 'scripts/dkdbkdc.webp',
    },
    {
      name: '军师恋盟',
      from: '喜剧大赛S2作品',
      tags: ['喜剧'],
      duration: 15,
      bgImage: 'scripts/jslm.webp',
    },
    {
      name: '鸣凤之死',
      from: '★ 话剧家改编',
      tags: ['民国', '悲剧'],
      duration: 15,
      bgImage: 'scripts/mfzs.webp',
    },
    {
      name: '减肥帮往事',
      from: '喜剧大赛S1作品',
      tags: ['喜剧'],
      duration: 10,
      bgImage: 'scripts/jfbws.webp',
    },
    {
      name: '小小世界的不速之客',
      from: '乌镇青赛2023作品',
      tags: ['先锋'],
      duration: 30,
      bgImage: 'scripts/xxsjdbszk.webp',
    },
  ],
  [
    {
      name: '八十一难',
      from: '喜人奇妙夜第1季作品',
      tags: ['喜剧'],
      duration: 15,
      bgImage: 'scripts/bsyn.webp',
    },
    {
      name: '我们的荆轲',
      from: '北京人艺话剧作品改编',
      tags: ['古装'],
      duration: 30,
      bgImage: 'scripts/wmdjk.webp',
    },
    {
      name: '心动的信号',
      from: '喜人奇妙夜第1季作品',
      tags: ['喜剧'],
      duration: 20,
      bgImage: 'scripts/xddxh.webp',
    },
    {
      name: '请你对我说个谎',
      from: '林蔚然作品改编',
      tags: ['女性', '爱情'],
      duration: 30,
      bgImage: 'scripts/qndwsgh.webp',
    },
    {
      name: '披星戴月的想你',
      from: '喜剧大师S1作品',
      tags: ['喜剧'],
      duration: 15,
      bgImage: 'scripts/pxdydxn.webp',
    },
    {
      name: '电子烟灰',
      from: '乌镇青赛2021|北国剧社作品',
      tags: ['先锋'],
      duration: 30,
      bgImage: 'scripts/dzyh.webp',
    },
    {
      name: '民国往事',
      from: '欢乐集结号作品',
      tags: ['小品'],
      duration: 20,
      bgImage: 'scripts/mgws.webp',
    },
    {
      name: '恋爱的犀牛',
      from: '廖一梅作品（节选）',
      tags: ['先锋', '爱情'],
      duration: 50,
      bgImage: 'scripts/ladxn.webp',
    },
  ],
  [
    {
      name: '越狱的夏天',
      from: '喜人奇妙夜第1季作品',
      tags: ['喜剧'],
      duration: 20,
      bgImage: 'scripts/yydxt.webp',
    },
    {
      name: '风声',
      from: '★ 同名电影改编',
      tags: ['革命', '谍战'],
      duration: 30,
      bgImage: 'scripts/fsmovie.webp',
    },
    {
      name: '爱情神话',
      from: '★ 同名电影改编|邵艺辉作品',
      tags: ['女性', '爱情'],
      duration: 25,
      bgImage: 'scripts/aqsh.webp',
    },
    {
      name: '蚌与珍珠',
      from: '乌镇青赛2023作品',
      tags: ['先锋', '女性'],
      duration: 30,
      bgImage: 'scripts/byzz.webp',
    },
    {
      name: '油漆未干',
      from: '勒内·福舒瓦作品',
      tags: ['喜剧'],
      duration: 120,
      bgImage: 'scripts/yqwg.webp',
    },
  ],
]

export default scripts
